### ISSUE TITLE
Can not run the script

### ISSUE THREAD

**Issue by iosoft** [Hadesy2k/sqliv#37]
Hello,

I can not run the script. I am not a Pythin person.

The error is -

```
#python sqliv.py -e google -t test.com

Traceback (most recent call last):
  File "sqliv.py", line 158, in <module>
    vulnerables = singleScan(args.target)
  File "sqliv.py", line 50, in singleScan
    io.stdout("crawling {}".format(url))
ValueError: zero length field name in format
```

**Comment by Hadesy2k** [comment]
Hi, thanks for reporting. Can you tell me your python2 version? It appears that the print function I wrote above does not support in Python versions 2.6 and below. You can check by running `python --version`. If it is 2.6 or below, try installing python 2.7 and above (*not python3*).

![image](https://i.imgur.com/qHZnz8b.png)

**Comment by iosoft** [comment]
I am using Python 2.6.6
How to fix this issue?

**Comment by Hadesy2k** [comment]
You have to update the python version to 2.7+
There are several ways of updating python. Please do some google as it depends on the system you are using.
