### ISSUE TITLE
Service Unreachable

### ISSUE THREAD

**Issue by YmmurcBan** [Hadesy2k/sqliv#38]
[MSG] [23:26:47] searching for websites with given dork
[503] Service Unreachable

**Comment by Hadesy2k** [comment]
The dork search use Google to get the results. It seems the Google blocked the query after continuous searching for 10-12 times. If you use browser and do dork searching, you can see that Google asks you to do image validation for search query.

I planned to put proxy function in the future. For now what you can do is wait for 15-30 mins or connect to VPN and try again. :)
