### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kali64amd** [Hadesy2k/sqliv#48]
I'm trying to install sqliv however getting this error, Please advise....

root@kali:~/Desktop/Newtool/sqliv# pip install -r requirements.txt
Collecting bs4 (from -r requirements.txt (line 1))
  Downloading bs4-0.0.1.tar.gz
Collecting termcolor (from -r requirements.txt (line 2))
  Downloading termcolor-1.1.0.tar.gz
Collecting terminaltables (from -r requirements.txt (line 3))
  Downloading terminaltables-3.1.0.tar.gz
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.4.1-py2.7.egg (from bs4->-r requirements.txt (line 1))
Building wheels for collected packages: bs4, termcolor, terminaltables
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /root/.cache/pip/wheels/84/67/d4/9e09d9d5adede2ee1c7b7e8775ba3fbb04d07c4f946f0e4f11
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /root/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
  Running setup.py bdist_wheel for terminaltables ... done
  Stored in directory: /root/.cache/pip/wheels/96/0c/9a/0ec2bcad2ac1fb1d0e4695879386460cec1a947cd7413d1b17
Successfully built bs4 termcolor terminaltables
Installing collected packages: bs4, termcolor, terminaltables
Successfully installed bs4-0.0.1 termcolor-1.1.0 terminaltables-3.1.0
root@kali:~/Desktop/Newtool/sqliv# clear

root@kali:~/Desktop/Newtool/sqliv# ls
libs     README.md         screenshots  sqliv.py
LICENSE  requirements.txt  setup.py     src
root@kali:~/Desktop/Newtool/sqliv# python2 setup.py -i
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.4.1-py2.7.egg (from bs4)
Requirement already satisfied: termcolor in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: terminaltables in /usr/local/lib/python2.7/dist-packages
Installation finished
Files are installed under /usr/share/sqliv
Run: sqliv --help
root@kali:~/Desktop/Newtool/sqliv# sqliv
Traceback (most recent call last):
  File "/usr/share/sqliv/sqliv.py", line 12, in <module>
    from src import search
  File "/usr/share/sqliv/src/search.py", line 6, in <module>
    from libs import google
  File "/usr/share/sqliv/libs/google.py", line 48, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
    
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
    
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'
root@kali:~/Desktop/Newtool/sqliv# sqliv
Traceback (most recent call last):
  File "/usr/share/sqliv/sqliv.py", line 12, in <module>
    from src import search
  File "/usr/share/sqliv/src/search.py", line 6, in <module>
    from libs import google
  File "/usr/share/sqliv/libs/google.py", line 48, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
    
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
    
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

**Comment by Hadesy2k** [comment]
hi, it is not the installation error, probably an error with dependencies in your system.
```
pip install --upgrade beautifulsoup4
pip install --upgrade html5lib
```
[Original Link](https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base)
