### ISSUE TITLE
SQLi checks probably won't work as expected

### ISSUE THREAD

**Issue by Ekultek** [Hadesy2k/sqliv#52]
You are currently checking:

    'SQL syntax error': "error in your SQL syntax",
    'Query failed': "Query failed",
    'Bad argument': "supplied argument is not a valid MySQL result resource in",
    'JET DBE error': "Microsoft JET Database Engine error '80040e14'",
    'Unknown error': "Error:unknown",
    'Fatal error': "Fatal error",
    'MySQL fetch': "mysql_fetch",
    'Syntax error': "Syntax error"

So you are checking 2 maybe 3 different types of DBMS's, what about PostgreSQL? Or SQLite?

Let's go through these really quick:

    'SQL syntax error': "error in your SQL syntax",  # mySQL
    'Query failed': "Query failed",  # possibly mySQL (not really a good test because a lot of queries can fail)
    'Bad argument': "supplied argument is not a valid MySQL result resource in",  # once again possibly mySQL, still not good because a bad argument does not prove SQLi
    'JET DBE error': "Microsoft JET Database Engine error '80040e14'",  # no idea what you're trying to find here maybe MsAccess?
    'Unknown error': "Error:unknown",  # not a good check, an unknown error would not be a SQLi point
    'Fatal error': "Fatal error",  # same as above
    'MySQL fetch': "mysql_fetch",  # fetch array is not a good indicator of SQLi because it expects a boolean
    'Syntax error': "Syntax error"  # this could work for MySQL

So now that we've gone through that you have two good checks for SQL injection. The rest are a bad check that will probably provide a false positive. My suggestion is to use something like this:

    # I'll give you two of each one, you can figure out the rest
    "MySQL": (r"SQL syntax.*MySQL", r"Warning.*mysql_.*"),
    "PostgreSQL": (r"PostgreSQL.*ERROR", r"Warning.*\Wpg_.*"),
    "Microsoft SQL Server": (r"OLE DB.* SQL Server", r"(\W|\A)SQL Server.*Driver"),
    "Microsoft Access": (r"Microsoft Access Driver", r"Access Database Engine"),
    "Oracle": (r"\bORA-[0-9][0-9][0-9][0-9]", r"Oracle error"),
    "IBM DB2": (r"CLI Driver.*DB2", r"DB2 SQL error"),
    "SQLite": (r"SQLite/JDBCDriver",r"System.Data.SQLite.SQLiteException"),
    "Sybase": (r"(?i)Warning.*sybase.*", None),

Not only are these good checks, but it's multiple database types and provides an easy extraction for what DBMS you are scanning.

Now lets get into your injection syntax, using `'` may provide an error. But that's not enough. Why would you just assume something is vulnerable from a single thrown error? What if the vulnerability lays inside of `)))/**/AND/**/1=1/**/(((` instead of a basic boolean check with `'`. I suggest you use something a little more exciting then adding `'` to each parameter, use a couple of syntax checks at each parameter instead of a single check and calling it good.

For example on a site like this: `www.vuln.com/index.php?id=10&page=10` just because query `id=10'` produces an error, doesn't mean query `page=10` is also going to produce the same error. Take it slow with the SQLi checks and check each query one at a time, otherwise you will skip vulnerable sites.

**Comment by Hadesy2k** [comment]
thanks for your feedback, I replaced the function with regex as you mentioned, and planned to add more detection cases. I will also add more vulnerability testing cases to the function. :)

**Comment by Ekultek** [comment]
[here](https://github.com/WhitewidowScanner/whitewidow/blob/master/lib/lists/inject.yml) is a YAML file that contains multiple injection syntax, can easily be ported to JSON or XML. Good luck with your SQLi scanner
