### ISSUE TITLE
MySQL and MariaDB

### ISSUE THREAD

**Issue by Ekultek** [Hadesy2k/sqliv#55]
These are the same things, specifying one as another is a very bad mistake, implement all MariaDB checks into MySQL

**Comment by sxobj04721517mamaobr** [comment]
Ekultek vc pode me passa seu skype

**Comment by Ekultek** [comment]
eu não uso skype desculpe

- Thomas Perkins

**Comment by sxobj04721517mamaobr** [comment]
ok desculpa

**Comment by sxobj04721517mamaobr** [comment]
kkkkkkkkkkkkkk

**Comment by Ekultek** [comment]
Specific reason as to why you want it?

**Comment by sxobj04721517mamaobr** [comment]
Trabalho  Marketing de email

**Comment by Ekultek** [comment]
@sxobj04721517mamaobr 

zeus.dork.scanner@gmail.com
