### ISSUE TITLE
the line 117 of setup.py where it prints a wrong path

### ISSUE THREAD

**Issue by westrength** [Hadesy2k/sqliv#59]
when install sqliv with command sudo python2 setup.py -i ,if Suddenly broken network,reinstall sqliv with sudo python2 setup.py -i,it will get error: executable file exists under /usr/share/sqliv.
I solved it with sudo rm -rf /usr/share/sqliv and sudo rm -rf /usr/bin/sqliv,then reinstall.It's ok.
Detailed:https://stackoverflow.com/questions/48003651/bash-cd-usr-share-sqliv-no-such-file-or-directory/48003956#48003956

**Comment by Hadesy2k** [comment]
How stupid of me, thanks for pointing it out. I fixed the incorrect line.

**Comment by westrength** [comment]
You are welcome!

2017年12月29日星期五，Ghost <notifications@github.com> 写道：
