### ISSUE TITLE
Feedback: Bing.com/Yandex.ru

### ISSUE THREAD

**Issue by Shazgul** [Hadesy2k/sqliv#6]
Hey Hadesy2k, is there an possibility to add bing.com & yandex.ru as other Search Engines beside Google? Google isn't the best choice because of the limitation of Search Querys.

**Comment by Hadesy2k** [comment]
Thanks for your suggestion. I do have a plan add search engine option (Yahoo or Bing). Meanwhile, I am kinda busy with other stuffs but I will push it in the near future.

**Comment by Hadesy2k** [comment]
Sry it took really long. Now the new script supports Bing, Google, and Yahoo search engines. :smiley:
