### ISSUE TITLE
[503] Service Unreachable

### ISSUE THREAD

**Issue by kdlsw** [Hadesy2k/sqliv#60]
`root@localhost:~/sqliv# python sqliv.py -d "inurl:index.php?id=" -e google
[MSG] [20:02:05] searching for websites with given dork
[503] Service Unreachable
`

I am running  Ubuntu 14.04.1 LTS, shouldn't be the network problem, it works on debian under the same network. Only google is not working, is it possible to debug it? Or make it more verbose?

**Comment by Hadesy2k** [comment]
It happens when you send several dork queries to Google. If you try on browser, you will see that Google asks to solve a captcha. Either you wait for a few minutes to make the request or try with another search engine (Bing or Yahoo). I will make an error message clear in the script.

**Comment by kreptoON** [comment]
oot@kr3pton:~/Desktop/sqliv# python sqliv.py -d "inurl:index.php?id=" -e google
Traceback (most recent call last):
  File "sqliv.py", line 13, in <module>
    from src.crawler import crawler
  File "/root/Desktop/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named nyawc.Options
.
.
.
this is my problem ..im running kali linux
